version: '3'

services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: fluentify-app-server
    volumes:
      - .:/dist
    ports:
      - 8080:8080
    restart: 'on-failure'
