// Code generated by mockery v2.40.3. DO NOT EDIT.

package handler_test

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// MockFeedbackHandler is an autogenerated mock type for the FeedbackHandler type
type MockFeedbackHandler struct {
	mock.Mock
}

type MockFeedbackHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeedbackHandler) EXPECT() *MockFeedbackHandler_Expecter {
	return &MockFeedbackHandler_Expecter{mock: &_m.Mock}
}

// GetCommunicationFeedback provides a mock function with given fields: c
func (_m *MockFeedbackHandler) GetCommunicationFeedback(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetCommunicationFeedback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFeedbackHandler_GetCommunicationFeedback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommunicationFeedback'
type MockFeedbackHandler_GetCommunicationFeedback_Call struct {
	*mock.Call
}

// GetCommunicationFeedback is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockFeedbackHandler_Expecter) GetCommunicationFeedback(c interface{}) *MockFeedbackHandler_GetCommunicationFeedback_Call {
	return &MockFeedbackHandler_GetCommunicationFeedback_Call{Call: _e.mock.On("GetCommunicationFeedback", c)}
}

func (_c *MockFeedbackHandler_GetCommunicationFeedback_Call) Run(run func(c echo.Context)) *MockFeedbackHandler_GetCommunicationFeedback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *MockFeedbackHandler_GetCommunicationFeedback_Call) Return(_a0 error) *MockFeedbackHandler_GetCommunicationFeedback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeedbackHandler_GetCommunicationFeedback_Call) RunAndReturn(run func(echo.Context) error) *MockFeedbackHandler_GetCommunicationFeedback_Call {
	_c.Call.Return(run)
	return _c
}

// GetPronunciationFeedback provides a mock function with given fields: c
func (_m *MockFeedbackHandler) GetPronunciationFeedback(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetPronunciationFeedback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFeedbackHandler_GetPronunciationFeedback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPronunciationFeedback'
type MockFeedbackHandler_GetPronunciationFeedback_Call struct {
	*mock.Call
}

// GetPronunciationFeedback is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockFeedbackHandler_Expecter) GetPronunciationFeedback(c interface{}) *MockFeedbackHandler_GetPronunciationFeedback_Call {
	return &MockFeedbackHandler_GetPronunciationFeedback_Call{Call: _e.mock.On("GetPronunciationFeedback", c)}
}

func (_c *MockFeedbackHandler_GetPronunciationFeedback_Call) Run(run func(c echo.Context)) *MockFeedbackHandler_GetPronunciationFeedback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *MockFeedbackHandler_GetPronunciationFeedback_Call) Return(_a0 error) *MockFeedbackHandler_GetPronunciationFeedback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeedbackHandler_GetPronunciationFeedback_Call) RunAndReturn(run func(echo.Context) error) *MockFeedbackHandler_GetPronunciationFeedback_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFeedbackHandler creates a new instance of MockFeedbackHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeedbackHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeedbackHandler {
	mock := &MockFeedbackHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
