// Code generated by mockery v2.40.3. DO NOT EDIT.

package handler_test

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// MockSceneHandler is an autogenerated mock type for the SceneHandler type
type MockSceneHandler struct {
	mock.Mock
}

type MockSceneHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSceneHandler) EXPECT() *MockSceneHandler_Expecter {
	return &MockSceneHandler_Expecter{mock: &_m.Mock}
}

// GetScene provides a mock function with given fields: c
func (_m *MockSceneHandler) GetScene(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetScene")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSceneHandler_GetScene_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScene'
type MockSceneHandler_GetScene_Call struct {
	*mock.Call
}

// GetScene is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockSceneHandler_Expecter) GetScene(c interface{}) *MockSceneHandler_GetScene_Call {
	return &MockSceneHandler_GetScene_Call{Call: _e.mock.On("GetScene", c)}
}

func (_c *MockSceneHandler_GetScene_Call) Run(run func(c echo.Context)) *MockSceneHandler_GetScene_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *MockSceneHandler_GetScene_Call) Return(_a0 error) *MockSceneHandler_GetScene_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSceneHandler_GetScene_Call) RunAndReturn(run func(echo.Context) error) *MockSceneHandler_GetScene_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSceneHandler creates a new instance of MockSceneHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSceneHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSceneHandler {
	mock := &MockSceneHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
