// Code generated by mockery v2.41.0. DO NOT EDIT.

package middleware_test

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthMiddleware is an autogenerated mock type for the AuthMiddleware type
type MockAuthMiddleware struct {
	mock.Mock
}

type MockAuthMiddleware_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthMiddleware) EXPECT() *MockAuthMiddleware_Expecter {
	return &MockAuthMiddleware_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function with given fields:
func (_m *MockAuthMiddleware) Verify() echo.MiddlewareFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 echo.MiddlewareFunc
	if rf, ok := ret.Get(0).(func() echo.MiddlewareFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.MiddlewareFunc)
		}
	}

	return r0
}

// MockAuthMiddleware_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockAuthMiddleware_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
func (_e *MockAuthMiddleware_Expecter) Verify() *MockAuthMiddleware_Verify_Call {
	return &MockAuthMiddleware_Verify_Call{Call: _e.mock.On("Verify")}
}

func (_c *MockAuthMiddleware_Verify_Call) Run(run func()) *MockAuthMiddleware_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthMiddleware_Verify_Call) Return(_a0 echo.MiddlewareFunc) *MockAuthMiddleware_Verify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthMiddleware_Verify_Call) RunAndReturn(run func() echo.MiddlewareFunc) *MockAuthMiddleware_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthMiddleware creates a new instance of MockAuthMiddleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthMiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthMiddleware {
	mock := &MockAuthMiddleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
