// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/gdsc-ys/fluentify-server/src/handler"
	"github.com/gdsc-ys/fluentify-server/src/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Init() *Initialization {
	app := InitializeFirebaseApp()
	userServiceImpl := service.UserServiceInit(app)
	userHandlerImpl := handler.UserHandlerInit(userServiceImpl)
	initialization := NewInitialization(userServiceImpl, userHandlerImpl)
	return initialization
}

// wire.go:

var firebaseApp = wire.NewSet(InitializeFirebaseApp)

var userServiceSet = wire.NewSet(service.UserServiceInit, wire.Bind(new(service.UserService), new(*service.UserServiceImpl)))

var userHandlerSet = wire.NewSet(handler.UserHandlerInit, wire.Bind(new(handler.UserHandler), new(*handler.UserHandlerImpl)))
