# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import internal_pb2 as internal__pb2


class PronunciationFeedbackServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PronunciationFeedback = channel.unary_unary(
                '/proto.PronunciationFeedbackService/PronunciationFeedback',
                request_serializer=internal__pb2.PronunciationFeedbackRequest.SerializeToString,
                response_deserializer=internal__pb2.PronunciationFeedbackResponse.FromString,
                )


class PronunciationFeedbackServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PronunciationFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PronunciationFeedbackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PronunciationFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.PronunciationFeedback,
                    request_deserializer=internal__pb2.PronunciationFeedbackRequest.FromString,
                    response_serializer=internal__pb2.PronunciationFeedbackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.PronunciationFeedbackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PronunciationFeedbackService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PronunciationFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.PronunciationFeedbackService/PronunciationFeedback',
            internal__pb2.PronunciationFeedbackRequest.SerializeToString,
            internal__pb2.PronunciationFeedbackResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class CommunicationFeedbackServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CommunicationFeedback = channel.unary_unary(
                '/proto.CommunicationFeedbackService/CommunicationFeedback',
                request_serializer=internal__pb2.CommunicationFeedbackRequest.SerializeToString,
                response_deserializer=internal__pb2.CommunicationFeedbackResponse.FromString,
                )


class CommunicationFeedbackServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CommunicationFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunicationFeedbackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CommunicationFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.CommunicationFeedback,
                    request_deserializer=internal__pb2.CommunicationFeedbackRequest.FromString,
                    response_serializer=internal__pb2.CommunicationFeedbackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.CommunicationFeedbackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommunicationFeedbackService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CommunicationFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.CommunicationFeedbackService/CommunicationFeedback',
            internal__pb2.CommunicationFeedbackRequest.SerializeToString,
            internal__pb2.CommunicationFeedbackResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
