// Code generated by mockery v2.40.3. DO NOT EDIT.

package service_test

import (
	model "github.com/gdsc-ys/fluentify-server/src/model"
	mock "github.com/stretchr/testify/mock"
)

// MockSceneService is an autogenerated mock type for the SceneService type
type MockSceneService struct {
	mock.Mock
}

type MockSceneService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSceneService) EXPECT() *MockSceneService_Expecter {
	return &MockSceneService_Expecter{mock: &_m.Mock}
}

// GetScene provides a mock function with given fields: id
func (_m *MockSceneService) GetScene(id string) (model.Scene, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetScene")
	}

	var r0 model.Scene
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (model.Scene, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) model.Scene); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Scene)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSceneService_GetScene_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScene'
type MockSceneService_GetScene_Call struct {
	*mock.Call
}

// GetScene is a helper method to define mock.On call
//   - id string
func (_e *MockSceneService_Expecter) GetScene(id interface{}) *MockSceneService_GetScene_Call {
	return &MockSceneService_GetScene_Call{Call: _e.mock.On("GetScene", id)}
}

func (_c *MockSceneService_GetScene_Call) Run(run func(id string)) *MockSceneService_GetScene_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSceneService_GetScene_Call) Return(_a0 model.Scene, _a1 error) *MockSceneService_GetScene_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSceneService_GetScene_Call) RunAndReturn(run func(string) (model.Scene, error)) *MockSceneService_GetScene_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSceneService creates a new instance of MockSceneService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSceneService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSceneService {
	mock := &MockSceneService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
